# Generated by Django 4.0.4 on 2022-05-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imageFile',
            field=models.FileField(max_length=50, upload_to='documents/%Y/%m/%d/images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='stegoFile',
            field=models.FileField(max_length=50, upload_to='documents/%Y/%m/%d/stego/'),
        ),
    ]
